--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1 (Debian 16.1-1.pgdg120+1)
-- Dumped by pg_dump version 16.1 (Debian 16.1-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: swen2
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO swen2;

--
-- Name: tourlogs; Type: TABLE; Schema: public; Owner: swen2
--

CREATE TABLE public.tourlogs (
    logid integer NOT NULL,
    date timestamp with time zone NOT NULL,
    comment text NOT NULL,
    difficulty integer NOT NULL,
    distance real NOT NULL,
    "time" double precision NOT NULL,
    rating integer NOT NULL,
    tourid integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.tourlogs OWNER TO swen2;

--
-- Name: tourlogs_logid_seq; Type: SEQUENCE; Schema: public; Owner: swen2
--

ALTER TABLE public.tourlogs ALTER COLUMN logid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tourlogs_logid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tours; Type: TABLE; Schema: public; Owner: swen2
--

CREATE TABLE public.tours (
    tourid integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    "from" text NOT NULL,
    "to" text NOT NULL,
    transporttype text NOT NULL,
    distance real NOT NULL,
    estimatedtime double precision NOT NULL,
    routeinformation text NOT NULL
);


ALTER TABLE public.tours OWNER TO swen2;

--
-- Name: tours_tourid_seq; Type: SEQUENCE; Schema: public; Owner: swen2
--

ALTER TABLE public.tours ALTER COLUMN tourid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tours_tourid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: swen2
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240317151342_InitialCreate	8.0.3
20240317202718_TourRelationshipTest	8.0.3
\.


--
-- Data for Name: tourlogs; Type: TABLE DATA; Schema: public; Owner: swen2
--

COPY public.tourlogs (logid, date, comment, difficulty, distance, "time", rating, tourid) FROM stdin;
\.


--
-- Data for Name: tours; Type: TABLE DATA; Schema: public; Owner: swen2
--

COPY public.tours (tourid, name, description, "from", "to", transporttype, distance, estimatedtime, routeinformation) FROM stdin;
\.


--
-- Name: tourlogs_logid_seq; Type: SEQUENCE SET; Schema: public; Owner: swen2
--

SELECT pg_catalog.setval('public.tourlogs_logid_seq', 13, true);


--
-- Name: tours_tourid_seq; Type: SEQUENCE SET; Schema: public; Owner: swen2
--

SELECT pg_catalog.setval('public.tours_tourid_seq', 20, true);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: swen2
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: tourlogs PK_tourlogs; Type: CONSTRAINT; Schema: public; Owner: swen2
--

ALTER TABLE ONLY public.tourlogs
    ADD CONSTRAINT "PK_tourlogs" PRIMARY KEY (logid);


--
-- Name: tours PK_tours; Type: CONSTRAINT; Schema: public; Owner: swen2
--

ALTER TABLE ONLY public.tours
    ADD CONSTRAINT "PK_tours" PRIMARY KEY (tourid);


--
-- Name: IX_tourlogs_tourid; Type: INDEX; Schema: public; Owner: swen2
--

CREATE INDEX "IX_tourlogs_tourid" ON public.tourlogs USING btree (tourid);


--
-- Name: tourlogs FK_tourlogs_tours_tourid; Type: FK CONSTRAINT; Schema: public; Owner: swen2
--

ALTER TABLE ONLY public.tourlogs
    ADD CONSTRAINT "FK_tourlogs_tours_tourid" FOREIGN KEY (tourid) REFERENCES public.tours(tourid) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

